kind = "mobile"
previewPath = "/brr-mobile/"
title = "BRR Liquor Soft Mobile"
version = "1.0.0"
id = "artifacts/brr-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/brr-mobile/" ]
localPort = 26176

[services.development]
run = "pnpm --filter @workspace/brr-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/brr-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/brr-mobile", "run", "serve" ]

[services.env]
PORT = "26176"
BASE_PATH = "/brr-mobile/"
